# Generated by Django 3.0.6 on 2021-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=111)),
                ('number', models.CharField(max_length=111)),
                ('desc', models.CharField(max_length=111)),
            ],
        ),
    ]
